name: waste_management
description: "A Flutter project for smart waste management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^2.1.0
  camera: ^0.10.1
  image_picker: ^0.8.7
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  excel: ^2.0.1
  geolocator: ^10.0.0
  dio: ^5.3.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/reset_password.png
    - assets/images/new_password.png
    - assets/images/news1.png
    - assets/images/news2.png
    - assets/NodesPlaces_DS.xlsx
    - assets/models/smart_waste_sorting_model.tflite
    - assets/images/Layer2.png
    - assets/images/Untitled-1.png
    - assets/images/Paper.png
    - assets/images/Plastic.jpg
    - assets/images/Metal.jpg
    - assets/images/Cardboard.jpg
    - assets/images/Glass.jpg
    - assets/images/Clothes.png
